export const VALID_TIPOLOGIE = [
  "Farmaco etico",
  "Parafarmaco uso umano",
  "Dispositivo medico",
  "Farmaco generico",
  "Farmaco da banco",
  "Alimento fini medici speciali",
  "Servizi",
  "Preparazione magistrale",
  "Farmaco veterinario",
  "Omeopatico uso umano",
  "Nessuna tipologia",
  "Parafarmaco erboristico",
  "Parafarmaco uso veterinario",
  "Presidio medico chirurgico",
  "Materia prima",
  "Medicinale veter.prefabbricato",
  "Codice di aggancio",
] as const;

export const MESI_ITALIANI: Record<string, number> = {
  gennaio: 1,
  febbraio: 2,
  marzo: 3,
  aprile: 4,
  maggio: 5,
  giugno: 6,
  luglio: 7,
  agosto: 8,
  settembre: 9,
  ottobre: 10,
  novembre: 11,
  dicembre: 12,
};
